#!/bin/bash
#
# Author: Prabakar, School of Computing and Information Sciences, FIU
#         prabakar@cis.fiu.edu
#         5/19/2010
#
# Do NOT edit this file (on Windows)
#
# If any script file is edited using Windows text editors
# there will be a CR (carriage return character) at the end
# of each line on the script file. This causes problem in executing
# the script file on any Unix/Linux system.
# This script file prompts for the name of a user script file
# present in the current directory, removes the extra CR character
# (if present) and rewrites the modified user script on the same file.
#

# check for correct number of arguments
if [ $# -gt 0 ]
 then # at least one argument is given
    echo Usage: $0 [with no argument]
    exit
fi

if [ -e $1 ]
 then
   #echo The script file $filename exists
   # strip trailing CR from each line of the file
   sed -e 's/
$//' $filename > zYxAbC
   /bin/mv -f zYxAbC $1
   chmod a+x $1
   echo "CR has been removed from all lines of the file $1"
 else
   echo The script file $filename does not exist
fi
exit
